---
- name: Update packages
  apt:
    update_cache: yes
    cache_valid_time: 3600

- name: Install vim
  apt:
    name: "vim"
    state: present

- name: Install curl
  apt:
    name: "curl"
    state: present

- name: Install wget
  apt:
    name: "wget"
    state: present

- name: Install unzip
  apt:
    name: "unzip"
    state: present

- name: Install less
  apt:
    name: "less"
    state: present

- name: Install dnsutils
  apt:
    name: "dnsutils"
    state: present

- name: Install net-tools
  apt:
    name: "net-tools"
    state: present

- name: Install sysstat
  apt:
    name: "sysstat"
    state: present

- name: Install htop
  apt:
    name: "htop"
    state: present

- name: Install jq
  apt:
    name: "jq"
    state: present

