---
- name: update packages - ubuntu
  apt:
    update_cache: yes
    cache_valid_time: 3600

- name: install package gcc - ubuntu
  apt:
    name: "gcc"
    state: present

- name: install package g++ - ubuntu
  apt:
    name: "g++"
    state: present

- name: install python-dev - ubuntu
  apt:
    name: "python-dev"
    state: present

- name: install python-setuptools - ubuntu
  apt:
    name: "python-setuptools"
    state: present

- name: install python-pip - ubuntu
  apt:
    name: "python-pip"
    state: present

- name: install python-virtualenv - ubuntu
  apt:
    name: "python-virtualenv"
    state: present

- name: install ipython - ubuntu
  pip:
    name: "ipython"
    state: present
