---
- name: install build-base for gcc - alpine
  apk:
    name: "build-base"
    state: present

- name: install ca-certificates - alpine
  apk:
    name: "ca-certificates"
    state: present

- name: install python2 - alpine
  apk:
    name: "python2"
    state: present

- name: install python2-dev - alpine
  apk:
    name: "python2-dev"
    state: present

- name: install py-setuptools - alpine
  apk:
    name: "py-setuptools"
    state: present

- name: install virtualenv - alpine
  apk:
    name: "py-virtualenv"
    state: present

- name: install ipython - alpine
  pip:
    name: "ipython"
    state: present
